### PR TITLE
Add type hints to find_stereo_pairs.py

### PR DESCRIPTION
**Pull request by PicoJr**
## Add type hints to `find_stereo_pairs.py`

* remove json from imports (Pycharm detects it as unused dependency)
* several methods return their class cf <https://stackoverflow.com/questions/33533148/how-do-i-type-hint-a-method-with-the-type-of-the-enclosing-class>, this is why 'hint' syntax is used.
* unsure which type hint to use for time parameters -> did not use any
* @foobarbecue : where is `find_covering_set` function? it appears `find_covering_set_poly` calls it but it is never defined?
* reformat code using Pycharm

### CODE REVIEW

**Review by foobarbecue — APPROVED** [review]
Looks great, thanks!

**Comment by godin-NGC** [comment]
Ahum guys... I may be mistaken but isn't the json import used [here](https://github.com/nasa-jpl/sstmp/blob/d0793d26f6dbd6bab3b78206d63916933015255f/src/moon/nacpl/find_stereo_pairs.py#L131) (and in a few other places)? I guess Pycharm is confused by the [import in the main function](https://github.com/nasa-jpl/sstmp/blob/d0793d26f6dbd6bab3b78206d63916933015255f/src/moon/nacpl/find_stereo_pairs.py#L501) but it definitely crashes in my workflow:

```
Traceback (most recent call last):
  File "/nacpl/find_nacs_mono.py", line 57, in <module>
    clize.run(bounding_box_mono, alt=from_polygon)
  File "/opt/miniconda3/envs/nacpl_env/lib/python3.7/site-packages/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/opt/miniconda3/envs/nacpl_env/lib/python3.7/site-packages/clize/runner.py", line 363, in run
    ret = cli(*args)
  File "/opt/miniconda3/envs/nacpl_env/lib/python3.7/site-packages/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "/nacpl/find_nacs_mono.py", line 26, in bounding_box_mono
    polygon=wkt.dumps(search_poly_shapely)
  File "/opt/miniconda3/envs/nacpl_env/lib/python3.7/site-packages/nacpl-0.1.0-py3.7.egg/nacpl/find_stereo_pairs.py", line 113, in __init__
    self.results = self._search_from_poly(*args, **kwargs)
  File "/opt/miniconda3/envs/nacpl_env/lib/python3.7/site-packages/nacpl-0.1.0-py3.7.egg/nacpl/find_stereo_pairs.py", line 131, in _search_from_poly
    count_resp = json.loads(count_resp.read())
NameError: name 'json' is not defined
```

**Comment by foobarbecue** [comment]
Um, whoops. Thanks.

**Comment by PicoJr** [comment]
I confirm I have the same issue running `find_nacs_mono.py`.

top import `import json` is indeed useful, it should not have been removed, sorry for the breakage.

I opened a PR that puts the import back.

**Comment by foobarbecue** [comment]
Looks like it might be time to write some unit tests ;-)

**Pull request merged**
